#Deployment Yaml for Findoc-cms

apiVersion: apps/v1
kind: Deployment
metadata:
  name: findoc-user
spec:
  selector:
    matchLabels:
      app: findoc-user
  template:
    metadata:
      labels:
        app: findoc-user
    spec:
      containers:
      - name: findoc-user
        image: 471112580006.dkr.ecr.ap-south-1.amazonaws.com/findost_user
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2277
        envFrom:
        - configMapRef:
            name: findoc-user-configmap
