const ROLE_TYPE = {
    SUPER_ADMIN: "SUPER ADMIN",
    ADMIN: "ADMIN",
    STAFF: "STAFF",
    SUB_Admin: "SUB ADMIN",
  };
  

  const PROFESSIONAL_DOCUMENT = {
    MANAGER: "MANAGER",
    ASSISTENT: "ASSISTENT INSURANCE AGENT",
    INSURANCE: "INSURANCE AGENT",
    REGIONAL: "REGIONAL_OFFICER",
    AUTHORIZED_PERSON : "AUTHORIZED PERSON",
    OTHER:"OTHER"
  };
 
  


  module.exports = {
      ROLE_TYPE,
      PROFESSIONAL_DOCUMENT
  }